spring:
  data:
    mongodb:
      database: test_db
      uri: mongodb://localhost:27017

server:
  port: 8090

logging:
  level:
    org.springframework.web: ERROR
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


